---
- name: Required packages
  import_tasks: packages.yml

- name: Join Host to AD
  import_tasks: adjoin.yml

- name: Configure SSSD
  import_tasks: sssd.yml

- name: Configure SSH
  import_tasks: sshd.yml
